/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Control.ImageControl;
import javax.swing.JFrame;

/**
 *
 * @author Lucas
 */
public class SaveScreen extends javax.swing.JFrame {
    
    private ImageControl img_control = new ImageControl();
    
    /**
     * Creates new form SaveScreen
     */
    public SaveScreen() {
        initComponents();
    }
    
    public void setControl(ImageControl img_control){
        this.img_control = img_control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_txt_field = new javax.swing.JTextField();
        info_label = new javax.swing.JLabel();
        save_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        error_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name_txt_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txt_fieldActionPerformed(evt);
            }
        });

        info_label.setText("Entre o nome do arquivo");

        save_button.setText("Salvar");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancelar");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        error_label.setText("Imagem não selecionada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error_label)
                    .addComponent(info_label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(save_button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancel_button))
                        .addComponent(name_txt_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(info_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(error_label)
                .addGap(18, 18, 18)
                .addComponent(name_txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_button)
                    .addComponent(cancel_button))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setSaveScreen(){
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        hideErrorMessage();
        setVisible(true);
    }
    
    private void hideErrorMessage(){
        error_label.setVisible(false);
    }
    
    private void showErrorMessage(){
        error_label.setVisible(true);
    }
    
    private void name_txt_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txt_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txt_fieldActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        try{
            String file_name = name_txt_field.getText();
            img_control.saveImage(file_name);
            hideErrorMessage();
            setVisible(false);
        }catch(NullPointerException exc){
            showErrorMessage();
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel error_label;
    private javax.swing.JLabel info_label;
    private javax.swing.JTextField name_txt_field;
    private javax.swing.JButton save_button;
    // End of variables declaration//GEN-END:variables
}
